"use client";

import * as React from "react";
import { SectionLabel } from "@/components/ui/SectionLabel";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { motion } from "framer-motion";
import { 
  Heart, Building2, Landmark, Briefcase, 
  Stethoscope, ShieldCheck, Scale, Globe,
  ArrowRight, Activity, Database, Lock,
  FileText, History, RefreshCw, Zap
} from "lucide-react";
import Link from "next/link";

export default function VerticalsPage() {
  const verticals = [
    {
      title: "HealthOS",
      sector: "Healthcare",
      subtitle: "Clinical AI governance for high-stakes outcomes.",
      body: "Applies the ABSTAIN model to out-of-distribution presentations. Governs every clinical recommendation using 100+ medical safety invariants. Structural exclusion of insurance status and financial capacity from clinical decisions.",
      status: "DESIGN PARTNER BETA",
      icon: Stethoscope,
      proofs: ["Diagnosis evaluation records", "Clinical causal records", "DPDP erasure proofs"]
    },
    {
      title: "FinanceOS",
      sector: "Finance & Banking",
      subtitle: "Trustworthy algorithms for the financial substrate.",
      body: "Constitutional credit models using 41 binding invariants (RBI-v4.2). Fraud-credit constitutional isolation prevents chain contamination. Merkle-anchored audit bundles for seamless regulatory examination.",
      status: "DESIGN PARTNER BETA",
      icon: Landmark,
      proofs: ["41-invariant checkpoints", "Exclusion provenance", "RBI compliance packages"]
    },
    {
      title: "AcademicOS",
      sector: "Education",
      subtitle: "AI-native assessment and reasoning evaluation.",
      body: "Powers the Education Platform via HSGE (step-grading) and SPRE (7D student digital twin). Probabilistic rank trajectory via Academic Predict. Constitutional exclusion of protected characteristics.",
      status: "LIVE — Production",
      icon: Activity,
      proofs: ["Reasoning gap certificates", "SPRE model snapshots", "Provenance records"]
    },
    {
      title: "LegalOS",
      sector: "Legal & Professional",
      subtitle: "Governed reasoning for the practice of law.",
      body: "Logical consistency evaluation for contract analysis and case reasoning. Provenance audits for every citation and legal recommendation generated by LLMs.",
      status: "ROADMAP",
      icon: Scale,
      proofs: ["Logical consistency proof", "Causal lineage"]
    },
    {
      title: "GovOS",
      sector: "Government & Sovereign",
      subtitle: "Constitutional AI for digital public infrastructure.",
      body: "Sovereign-ready AI governance. Data residency and jurisdiction enforcement at the execution layer. Transparent, auditable citizen-facing AI services.",
      status: "ROADMAP",
      icon: Globe,
      proofs: ["Sovereignty proof", "Immutable audit chain"]
    },
    {
      title: "EnterpriseOS",
      sector: "Corporate Infrastructure",
      subtitle: "Unified governance for the multi-agent enterprise.",
      body: "Powers AI Artifact Studio. Constitutional oversight for every agent, prompt, and tool deployed across the organisation. Authority hierarchy for AI fleets.",
      status: "EARLY ACCESS",
      icon: Building2,
      proofs: ["Authority records", "Artifact lifecycle logs"]
    }
  ];

  return (
    <main className="relative z-10 max-w-7xl mx-auto px-6 lg:px-12 py-24 space-y-48 min-h-screen">
      {/* Background Grid Pattern */}
      <div className="fixed inset-0 pointer-events-none z-0 opacity-[0.08] bg-[linear-gradient(to_right,#0A0E1A_1px,transparent_1px),linear-gradient(to_bottom,#0A0E1A_1px,transparent_1px)] bg-[size:40px_40px]"></div>

      {/* HERO */}
      <section className="max-w-4xl pt-12">
        <motion.div
           initial={{ opacity: 0, y: 20 }}
           whileInView={{ opacity: 1, y: 0 }}
           viewport={{ once: true }}
           transition={{ duration: 0.6 }}
        >
          <SectionLabel>VERTICAL INSTANTIATIONS</SectionLabel>
        </motion.div>
        
        <motion.h1 
          className="text-6xl md:text-8xl font-display mt-8 leading-[1.1]"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.1 }}
        >
          One platform.<br />
          <span className="text-gold">Infinite instantiations.</span>
        </motion.h1>

        <motion.p 
          className="mt-8 text-xl md:text-2xl text-text-secondary font-sans max-w-[800px] leading-relaxed"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          ATRIYA is the constitutional substrate. Vertical &quot;OS&quot; layers add 
          domain-specific adapters, rule sets, and primitives for 
          specialised sectors. One substrate. Total domain depth.
        </motion.p>
      </section>

      {/* VERTICALS GRID */}
      <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {verticals.map((v, idx) => (
           <motion.div 
             key={idx}
             initial={{ opacity: 0, y: 20 }}
             whileInView={{ opacity: 1, y: 0 }}
             viewport={{ once: true }}
             transition={{ duration: 0.6, delay: idx * 0.1 }}
             className="group flex flex-col justify-between p-10 bg-white border border-border rounded-3xl hover:border-gold/30 hover:bg-bg-secondary transition-all shadow-sm hover:shadow-md"
           >
              <div className="space-y-8">
                 <div className="flex justify-between items-start">
                    <div className="h-12 w-12 bg-bg-secondary rounded flex items-center justify-center group-hover:bg-gold/10 transition-colors">
                       <v.icon className="text-gold" size={24} />
                    </div>
                    <Badge variant={v.status.includes("LIVE") ? "live" : "muted"}>{v.status}</Badge>
                 </div>
                 
                 <div className="space-y-2">
                    <p className="text-[10px] font-mono font-bold text-text-tertiary uppercase tracking-widest">{v.sector}</p>
                    <h3 className="text-3xl font-display text-text-primary group-hover:text-gold transition-colors">{v.title}</h3>
                 </div>
                 
                 <p className="text-lg text-text-secondary font-sans leading-relaxed">{v.body}</p>
                 
                 <div className="pt-4 border-t border-border/50">
                    <p className="text-[10px] font-mono text-text-tertiary uppercase tracking-widest mb-4">Structural Proofs Generated</p>
                    <div className="flex flex-wrap gap-2">
                       {v.proofs.map((proof, i) => (
                          <span key={i} className="px-3 py-1 bg-white border border-border rounded-md text-[10px] font-sans text-text-secondary">
                             {proof}
                          </span>
                       ))}
                    </div>
                 </div>
              </div>
              
              <div className="mt-12">
                 <Button variant="ghost" className="p-0 text-gold hover:text-gold-hover hover:bg-transparent flex items-center gap-2 group/btn">
                    Explore {v.sector} Solution <ArrowRight className="group-hover/btn:translate-x-1 transition-transform" size={16} />
                 </Button>
              </div>
           </motion.div>
        ))}
      </section>

      {/* UNIVERSAL PRIMITIVES CALLOUT */}
      <section className="bg-bg-tertiary rounded-3xl p-12 lg:p-24 border border-border flex flex-col md:flex-row gap-12 items-center justify-between">
        <div className="space-y-6 max-w-xl">
          <SectionLabel>THE UNIVERSAL CONSTANT</SectionLabel>
          <h2 className="text-4xl md:text-5xl font-display">One engine. Total reuse.</h2>
          <p className="text-xl text-text-secondary font-sans leading-relaxed">
             While sector verticalisation provides domain depth, 75% of the 
             reasoning engine and 100% of the governance substrate remain 
             identical across all OS instantiations.
          </p>
        </div>
        <Button size="lg" className="h-16 px-12 group">
          <Link href="/platform/architecture" className="flex items-center gap-2 text-lg">View Platform Architecture <ArrowRight className="group-hover:translate-x-1 transition-transform" /></Link>
        </Button>
      </section>

      {/* FINAL CTA */}
      <section className="max-w-4xl mx-auto text-center space-y-12">
          <h2 className="text-4xl md:text-6xl font-display">Your sector needs governed AI.</h2>
          <div className="pt-8">
            <Button size="lg" className="h-16 px-12 group">
               <Link href="/contact" className="flex items-center gap-3 text-lg">Talk to our team <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" /></Link>
            </Button>
          </div>
      </section>
    </main>
  );
}
