"use client";

import * as React from "react";
import { SectionLabel } from "@/components/ui/SectionLabel";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { motion } from "framer-motion";
import { 
  CheckCircle2, ArrowRight, ShieldCheck, Activity, 
  Database, UserCheck, Scale, History,
  Lock, AlertTriangle, FileCheck, Layers,
  Cpu, Code2, Globe, BrainCircuit, Eraser, MapPin
} from "lucide-react";
import Link from "next/link";

export default function CertificationsPage() {
  const proofs = [
    {
      title: "Deterministic Replay Certificate",
      desc: "Mathematical proof that an AI decision can be exactly reproduced given the same input and governance state.",
      anchor: "EU AI Act Art.13",
      useCase: "Presenting evidence in a credit refusal dispute to prove the same rules applied uniformly."
    },
    {
      title: "Immutable Audit Chain",
      desc: "A hash-linked record of every state transition, data access, and decision made during AI execution.",
      anchor: "RBI AI Guidelines",
      useCase: "Providing a complete decision trail for internal audit or regulatory examination."
    },
    {
      title: "Erasure Certificate (PURGED)",
      desc: "Verifiable proof that specific data has been irrevocably deleted across the substrate and all engines.",
      anchor: "GDPR Art.17 / DPDP §12",
      useCase: "Fulfilling a user's right-to-be-forgotten request with absolute technical certainty."
    },
    {
      title: "Causal Lineage Proof",
      desc: "Cryptographic binding between specific input data points and the resulting AI output.",
      anchor: "India DPDP Act",
      useCase: "Proving that only authorised and consented data sources were used for a specific output."
    },
    {
      title: "Fail-Closed Attestation",
      desc: "Proof that the system refused the request when governance constraints were unsatisfiable.",
      anchor: "EU AI Act Art.9",
      useCase: "Demonstrating structural risk management to an enterprise insurer or CISO."
    },
    {
      title: "Authority Delegation Record",
      desc: "Permanent record of the authority class and identity used for a specific governed action.",
      anchor: "EU AI Act Art.14",
      useCase: "Establishing accountability of human oversight in high-stakes automated decisions."
    },
    {
      title: "Consent Scope Attestation",
      desc: "Documented evaluation of an AI request against the declared and legally consented scope of use.",
      anchor: "DPDP Act §6",
      useCase: "Audit verification for data fiduciary obligations regarding purpose-binding."
    },
    {
      title: "Jurisdictional Residency Proof",
      desc: "Proof that the execution and data processing occurred within the legally required sovereign boundary.",
      anchor: "RBI / DPDP Residency",
      useCase: "Satisfying data localization requirements for sovereign government or financial deployments."
    }
  ];

  return (
    <main className="relative z-10 max-w-7xl mx-auto px-6 lg:px-12 py-24 space-y-48 min-h-screen">
      {/* Background Grid Pattern Overlay */}
      <div className="fixed inset-0 pointer-events-none z-0 opacity-[0.08] bg-[linear-gradient(to_right,#0A0E1A_1px,transparent_1px),linear-gradient(to_bottom,#0A0E1A_1px,transparent_1px)] bg-[size:40px_40px]"></div>

      {/* HERO */}
      <section className="max-w-4xl pt-12">
        <motion.div
           initial={{ opacity: 0, y: 20 }}
           whileInView={{ opacity: 1, y: 0 }}
           viewport={{ once: true }}
           transition={{ duration: 0.6 }}
        >
          <SectionLabel>EVIDENCE & PROOF</SectionLabel>
        </motion.div>
        
        <motion.h1 
          className="text-6xl md:text-8xl font-display mt-8 leading-[1.1]"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.1 }}
        >
          Compliance proofs.<br />
          <span className="text-gold italic">Not compliance reports.</span>
        </motion.h1>

        <motion.p 
          className="mt-8 text-xl md:text-2xl text-text-secondary font-sans max-w-[800px] leading-relaxed"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          Eight types of verifiable output generated by ATRIYA as a 
          structural consequence of execution. Present them to any regulator, 
          auditor, or court.
        </motion.p>
      </section>

      {/* PROOF TYPES GRID */}
      <section className="space-y-16">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-px bg-border border border-border rounded-2xl overflow-hidden">
           {proofs.map((proof, idx) => (
             <div key={idx} className="bg-white p-12 space-y-8 group transition-colors">
                <div className="flex justify-between items-start">
                   <h3 className="text-2xl font-bold font-sans group-hover:text-gold transition-colors">{proof.title}</h3>
                   <span className="text-[10px] font-mono text-text-tertiary bg-bg-secondary px-3 py-1 rounded border border-border">{proof.anchor}</span>
                </div>
                <p className="text-lg text-text-secondary font-sans leading-relaxed">{proof.desc}</p>
                <div className="pt-4 border-t border-border/50">
                   <p className="text-[10px] font-mono text-text-tertiary uppercase tracking-widest font-bold mb-2">Example Use Case</p>
                   <p className="text-sm text-text-tertiary font-sans italic">{proof.useCase}</p>
                </div>
             </div>
           ))}
        </div>
      </section>

      {/* FINAL CERTIFICATIONS CTA */}
      <section className="max-w-4xl mx-auto text-center space-y-12 bg-bg-tertiary p-12 md:p-24 rounded-[3rem] border border-border">
          <SectionLabel>SAMPLE DOCUMENTATION</SectionLabel>
          <h2 className="text-4xl md:text-6xl font-display">Seen by humans. <br /> Proven by math.</h2>
          <p className="text-xl text-text-secondary font-sans font-medium px-4">
             Request sample compliance artifacts and see how ATRIYA 
             generates proof for your specific regulatory context.
          </p>
          <div className="pt-8">
            <Button size="lg" className="h-16 px-16 group">
              <Link href="/contact" className="flex items-center gap-3">Request Sample Package <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" /></Link>
            </Button>
          </div>
      </section>
    </main>
  );
}
